# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_meeting_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='username',
        ),
        migrations.AddField(
            model_name='members',
            name='email',
            field=models.EmailField(default='abc@aaa.com', max_length=128),
        ),
    ]
