# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20170705_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_zone',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
