# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20170706_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
